### ISSUE TITLE
Use this programatically

### ISSUE THREAD

**Issue by luixal** [alan2207/strapi-plugin-sync-roles-permissions#1]
Hi,

I just wrote something similar to this, but to be used on server first run. I haven't check the json structure, sure it's different because I made up mine to my (simple) needs.

Anyhow, I guess I'd be able to call the `updateRoles` using something like:

```js
strapi.query('sync-roles-permissions').update(myJsonObject);
```

but would be great to have a working example in the readme together with a json structure example :)

Thanks for the plugin, great work!

**Comment by alan2207** [comment]
Hi @luixal 

That's exactly how I solved it first, importing the roles from the `bootstrap` function, but then I realized it is better to use it as a plugin and not run it programatically as I noticed some DB errors when running it for the first time. Also, there was no interface to update the roles if I changed it in the meantime, so I had to delete the generated JSON files and re-run the migrating function from `bootstrap.js` again, which is not ideal.

With the plugin, you are in total control when you want to populate or update your roles and permissions.

Is there a particular reason you need it to be programmatic, and not add roles via plugin?

**Comment by luixal** [comment]
The use case comes when i build an app and I don't want to be populating strapi's config by hand on each deploy. Right now, I'm creating the admin user and user's permissions (public and authenticated) on first run.

I haven't noticed errors in the db in the app I'm working in right now, but can't be sure in other scenarios/configs.

I'll give it a try calling your function on bootstrap if it's possible. Could you share your json structure so it's easier?

Thanks!

**Comment by alan2207** [comment]
How and where do you plan to export current roles in order to import them later? How do you plan to update roles and permissions?

You can check the structure by exporting the roles via the plugin. It requires that exact structure.

**Comment by luixal** [comment]
Maybe we are talking about different things. When I close a version, I already know the permissions needed, that's the point where I can export permissions from pre or dev environments, then, instead of manually get into the production env and import the permissions, I plan on importing them programatically on server's first run.

I'll check the structure exported and try to do this by calling the `updatedRoles` function from bootstrap fn.

Thanks!

**Comment by alan2207** [comment]
Well, in that case you can try to use the `updateRoles` function from `services`:

This is how you can invoke it:

```js
await strapi.plugins["sync-roles-permissions"].services["sync-roles-permissions"].updateRoles(roles);
```

You can also use the `getRoles` function from service to somehow grab the existing roles and permissions structure and export it somewhere:

```js
await strapi.plugins["sync-roles-permissions"].services["sync-roles-permissions"].getRoles();
```
